### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by bennypowers** [esm-bundle/autopublish-template#17]
```
yarn test:unit  
yarn run v1.16.0
$ mocha -r chai/register-expect 'node-test/**/*.*'
/Users/bennyp/Documents/oidc-client/node_modules/yargs/yargs.js:1163
      else throw err
           ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/bennyp/Documents/oidc-client/node-test/main.test.mjs
    at Object.Module._extensions..mjs (internal/modules/cjs/loader.js:819:9)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at /Users/bennyp/Documents/oidc-client/node_modules/mocha/lib/mocha.js:311:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/bennyp/Documents/oidc-client/node_modules/mocha/lib/mocha.js:308:14)
    at Mocha.run (/Users/bennyp/Documents/oidc-client/node_modules/mocha/lib/mocha.js:849:10)
    at Object.exports.singleRun (/Users/bennyp/Documents/oidc-client/node_modules/mocha/lib/cli/run-helpers.js:108:16)
    at exports.runMocha (/Users/bennyp/Documents/oidc-client/node_modules/mocha/lib/cli/run-helpers.js:143:13)
    at Object.exports.handler (/Users/bennyp/Documents/oidc-client/node_modules/mocha/lib/cli/run.js:305:3)
    at Object.runCommand (/Users/bennyp/Documents/oidc-client/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/Users/bennyp/Documents/oidc-client/node_modules/yargs/yargs.js:1087:28)
    at Object.parse (/Users/bennyp/Documents/oidc-client/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (/Users/bennyp/Documents/oidc-client/node_modules/mocha/lib/cli/cli.js:68:6)
    at Object.<anonymous> (/Users/bennyp/Documents/oidc-client/node_modules/mocha/bin/mocha:133:29)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
```

main.test.js is unchanged.

rollup.config.js
```js
import resolve from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import globals from "rollup-plugin-node-globals";
import builtins from "rollup-plugin-node-builtins";

function createConfig(format) {
  const dir = format === "module" ? "esm" : format;
  return {
    input: require.resolve("oidc-client/index.js"),
    output: {
      file: `${dir}/index.js`,
      format
    },
    plugins: [
      resolve(),
      builtins(),
      globals(),
      commonjs({ preferBuiltins: false })
    ]
  };
}

export default [createConfig("module"), createConfig("system")];
```

**Comment by joeldenning** [comment]
You must be using nodejs@13.2 or higher for node `import` to work by default. See https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V13.md#13.2.0.

Alternatively, you can run node with `--experimental-modules` for it to work.

**Comment by bennypowers** [comment]
onboarding docs should include an `nvm use v13` step?

**Comment by joeldenning** [comment]
👍 would you mind adding that to the new-repo-instructions?
